# C++进阶(26) 异常处理

## 26.1 异常的概念

异常是程序在运行过程中可能产生的意外情况。

异常与Bug 的区别：异常是程序运行时可预料的执行分支，而Bug是程序中的错误，而非预期的运行方式。

异常：

- 运行时产生除0的情况
- 需要打开的外部文件不存在
- 数组访问越界

Bug：

- 使用野指针
- 堆数组使用后未释放
- 选择排序无法处理长度为0的数组

C语言中处理异常的方式：`if ... else ... `

```C
void func(...){
    if (是否产生异常){
        正常处理
    }
    else{
		异常情况处理   
    }
}
```

> 实验26-1 C语言中除法异常处理



改进 ：`setjmp()`  `longjmp()` 暴力跳转。

C语言中异常处理缺点：C语言中异常处理逻辑混出大量异常处理代码。

</br>

## 26.2 C++ 中异常处理

C++中内置异常处理语法：`try ... catch ...` ，其中 `try`  语句处理正常代码逻辑， `catch` 处理异常情况。

```C++
try{
    double r = divide(1, 0);
}
catch(...){
    cout << "Divided by zero..." << endl;
}
```

C++ 中通过 `throw` 语句抛出异常信息，抛出的异常必须被 `catch` 处理。

- 当前函数能处理异常，程序往下执行
- 当前函数无法处理异常，则函数停止执行，并返回。

异常处理的传播：未被处理的异常会顺着函数调用栈向上传播，直到被处理位置，否则程序将停止执行。

> 实验26-2 cpp中 try... catch .. 语句



对于同一个 `try` 语句 跟上多个 `catch` 语句，

- catch 语句可以定义具体的异常类型

- 不同类型异常可以由不同 `catch` 语句负责处理

-  `try` 语句中可以抛出任何类型的异常

- `catch(...)` 用于处理所有类型异常

- 任何异常都只能被捕捉一次

  

异常处理的匹配规则：异常抛出后，从上而下严格匹配每个 `catch` 语句处理的类型。类型严格匹配，不能进行类型转换。

> 实验26-3 cpp 中异常处理



## 26.3 catch 语句

`catch` 语句可以抛出异常，但在 `catch` 中抛出的异常需要外层的 `try... catch ... ` 捕获。

```C++
try{
    func();
}
catch(int i){
    throw i;
}
catch(...){
    throw;
}
```

> 实验26-4 在 `catch` 中抛出异常



## 26.4 自定义异常类

catch 异常符合赋值兼容性原则。所以，父类异常分支在下面，子类异常分支在上面。

> 实验26-5 自定义Exception 类



## 26.5 标准库中的异常处理

头文件 `stdexcept` 。













